# Default values for ci-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  image: tachingchen/skaffold-hello-world
  pullPolicy: IfNotPresent