sudo: required

dist: trusty

branches:
  only:
  - master

language: go

go:
  - 1.10.2

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo sysctl net.ipv6.conf.all.disable_ipv6=0

script:
  - cd ${TRAVIS_BUILD_DIR}/codebase
  - ./build.sh